# Statistika Inferential

In [ ]:
#Import semua library yang mungkin dibutuhkan
import statistics
import numpy as np

#tabel nilai z_score
z_table = {
    -3.0: 0.0013, -2.9: 0.0019, -2.8: 0.0026, -2.7: 0.0035, -2.6: 0.0047,
    -2.5: 0.0062, -2.4: 0.0082, -2.3: 0.0107, -2.2: 0.0139, -2.1: 0.0179,
    -2.0: 0.0228, -1.9: 0.0287, -1.8: 0.0359, -1.7: 0.0446, -1.6: 0.0548,
    -1.5: 0.0668, -1.4: 0.0808, -1.3: 0.0968, -1.2: 0.1151, -1.1: 0.1357,
    -1.0: 0.1587, -0.9: 0.1841, -0.8: 0.2119, -0.7: 0.2420, -0.6: 0.2743,
    -0.5: 0.3085, -0.4: 0.3446, -0.3: 0.3821, -0.2: 0.4207, -0.1: 0.4602,
     0.0: 0.5000,  0.1: 0.5398,  0.2: 0.5793,  0.3: 0.6179,  0.4: 0.6554,
     0.5: 0.6915,  0.6: 0.7257,  0.7: 0.7580,  0.8: 0.7881,  0.9: 0.8159,
     1.0: 0.8413,  1.1: 0.8643,  1.2: 0.8849,  1.3: 0.9032,  1.4: 0.9192,
     1.5: 0.9332,  1.6: 0.9452,  1.7: 0.9554,  1.8: 0.9641,  1.9: 0.9713,
     2.0: 0.9772,  2.1: 0.9821,  2.2: 0.9861,  2.3: 0.9893,  2.4: 0.9918,
     2.5: 0.9938,  2.6: 0.9953,  2.7: 0.9965,  2.8: 0.9974,  2.9: 0.9981,
     3.0: 0.9987
}

## Soal 1. Probabilitas



Sebuah perusahaan mengklaim bahwa mesin produksi mereka menghasilkan botol dengan volume rata-rata 500 ml dan standar deviasi 25 ml. Seorang inspektur ingin menguji apakah klaim tersebut benar dengan mengambil sampel acak dari 100 botol. Dari sampel tersebut, inspektur menemukan bahwa rata-rata volume botol adalah 495 ml. Hitunglah probabilitas bahwa rata-rata volume botol dalam sampel sebesar 495 ml atau kurang, berdasarkan klaim perusahaan.



In [ ]:
mean = 500
std_dev = 25
ukuran_sampel = 100
mean_sampel = 495

def cal_standard_error(std_dev, ukuran_sampel):
    return std_dev / (ukuran_sampel ** 0.5)

def cal_z_score(sample_mean, population_mean, std_error):
    return (sample_mean - population_mean) / std_error

std_error_mean = cal_standard_error(std_dev, ukuran_sampel)

# hitung nilai z
z_score = cal_z_score(mean_sampel, mean, std_error_mean)

p_value = z_table[round(z_score, 1)]
print(f"Z-score: {z_score}")
print(f"Probabilitas bahwa rata-rata volume botol dalam sampel sebesar {mean_sampel} ml atau kurang adalah {p_value:.4f}")

Z-score: -2.0
Probabilitas bahwa rata-rata volume botol dalam sampel sebesar 495 ml atau kurang adalah 0.0228


Expected output:


```
Probabilitas bahwa rata-rata volume botol dalam sampel sebesar 495 ml atau kurang adalah 0.0228
```

---

## Soal 2. Menghitung Interval Kepercayaan



Sebuah penelitian dilakukan untuk mengukur rata-rata berat badan dari sebuah populasi ikan di sebuah danau. Dari sampel acak sebanyak 50 ikan, rata-rata berat badan yang ditemukan adalah 2.5 kg dengan standar deviasi 0.4 kg. Hitunglah rata-rata berat badan ikan di danau tersebut dengan interval kepercayaan 95%.

In [ ]:
def calculate_confidance_interval(sample_mean, std_dev, n, z_score):
  margin_error = z_score * (std_dev/np.sqrt(n))
  lower_bound = sample_mean - margin_error
  upper_bound = sample_mean + margin_error
  return lower_bound, upper_bound

sample_mean = 2.5
std_dev = 0.4
n = 50
z_score = 1.96

lower_bound, upper_bound = calculate_confidance_interval(sample_mean, std_dev, n, z_score)
print(f"Rata-rata berat badan ikan di danau tersebut dengan interval kepercayaan 95% adalah ({lower_bound:.3f}, {upper_bound:.3f})")

Rata-rata berat badan ikan di danau tersebut dengan interval kepercayaan 95% adalah (2.389, 2.611)


Expected output:


```
Rata-rata berat badan ikan di danau tersebut dengan interval kepercayaan 95% adalah (2.389, 2.611)
```





---



---



## Soal 3. Anova

Anda diberikan data dari empat kelompok berbeda yang mewakili hasil eksperimen pada empat kondisi yang berbeda:

*    group1 = [15, 18, 21, 19, 20, 22]
*    group2 = [25, 28, 30, 27, 26, 29]
*    group3 = [35, 38, 37, 36, 34, 39]
*    group4 = [45, 48, 46, 47, 44, 49]


Buatlah sebuah fungsi Python yang melakukan uji ANOVA satu arah untuk menguji apakah terdapat perbedaan signifikan di antara keempat kelompok tersebut pada tingkat signifikansi 0.05. Tampilkan nilai F, nilai kritis, dan kesimpulan uji.

In [ ]:
# F - ratio = varian antar grup/varian dalam grup
# f-ratio = akar rataan diantara/akar rataan di dalam

def mean(data):
  return sum(data)/len(data)

def sum_of_squares(data, overall_mean):
  #cari rata-rata keseluruhan data
  return sum((x - overall_mean)**2 for x in data)

def anova(group1, group2, group3, group4, alpha = 0.05):
  all_data = group1 + group2 + group3 + group4
  overall_mean = mean(all_data)

  # cari rata-rata kelompok
  mean1 = mean(group1)
  mean2 = mean(group2)
  mean3 = mean(group3)
  mean4 = mean(group4)

  # menghitung total sum square
  SST = sum_of_squares(all_data, overall_mean)

  #menghitung total group sum square
  SSW = sum_of_squares(group1, mean1) + sum_of_squares(group2, mean2) + sum_of_squares(group3, mean3) + sum_of_squares(group4, mean4)

  #SSB Menghitung group sum square antara
  n1 = len(group1)
  n2 = len(group2)
  n3 = len(group3)
  n4 = len(group4)

  # len * (rataan - rataan total)**2
  SSB = n1*(mean1-overall_mean)**2 + n2*(mean2-overall_mean)**2 + n3*(mean3-overall_mean)**2 + n4*(mean4-overall_mean)**2

  #derajat kebebasan
  dk_between = 4 - 1 #jumlah kelompok - 1 atau k-1
  dk_within = len(all_data) - 4 #total data - jumlah kelompok atau (N-k)

  MSB = SSB/dk_between
  MSW = SSW/dk_within

  F = MSB/MSW

  f_critical = 3.555

  result = f"Terdapat perbedaan signifikan di antara kelompok" if F > f_critical else "Tidak ada bukti yang cukup bahwa Terdapat perbedaan signifikan di antara kelompok"
  return F, dk_between, dk_within, f_critical, result

group1 = [15, 18, 21, 19, 20, 22]
group2 = [25, 28, 30, 27, 26, 29]
group3 = [35, 38, 37, 36, 34, 39]
group4 = [45, 48, 46, 47, 44, 49]

F, dk_between, dk_within, f_critical,result = anova(group1, group2, group3, group4)
print(f"Nilai F: {F:.10f}")
print(f"Derajat kebebasan antar kelompok: {dk_between}")
print(f"Derajat kebebasan dalam kelompok: {dk_within}")
print(f"Nilai F kritikal: {f_critical:.3f}")
print(f"Kesimpulan: {result}")

Nilai F: 199.0800000000
Derajat kebebasan antar kelompok: 3
Derajat kebebasan dalam kelompok: 20
Nilai F kritikal: 3.555
Kesimpulan: Terdapat perbedaan signifikan di antara kelompok


ouput:

```
Nilai F: 199.07999999999998
Derajat kebebasan antar kelompok: 3
Derajat kebebasan dalam kelompok: 20
Nilai kritis F: 3.098
Kesimpulan: Terdapat perbedaan signifikan di antara kelompok
```



---



---

